<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210318133759 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX IDX_DE92C5CF26F859E2');
        $this->addSql('CREATE TEMPORARY TABLE __temp__annee AS SELECT id, diplome_id, nom, numero_annee FROM annee');
        $this->addSql('DROP TABLE annee');
        $this->addSql('CREATE TABLE annee (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, diplome_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL COLLATE BINARY, numero_annee INTEGER NOT NULL, CONSTRAINT FK_DE92C5CF26F859E2 FOREIGN KEY (diplome_id) REFERENCES diplome (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO annee (id, diplome_id, nom, numero_annee) SELECT id, diplome_id, nom, numero_annee FROM __temp__annee');
        $this->addSql('DROP TABLE __temp__annee');
        $this->addSql('CREATE INDEX IDX_DE92C5CF26F859E2 ON annee (diplome_id)');
        $this->addSql('DROP INDEX IDX_C1765B6377EF1B1E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__departement AS SELECT id, ecole_id, nom FROM departement');
        $this->addSql('DROP TABLE departement');
        $this->addSql('CREATE TABLE departement (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ecole_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_C1765B6377EF1B1E FOREIGN KEY (ecole_id) REFERENCES ecole (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO departement (id, ecole_id, nom) SELECT id, ecole_id, nom FROM __temp__departement');
        $this->addSql('DROP TABLE __temp__departement');
        $this->addSql('CREATE INDEX IDX_C1765B6377EF1B1E ON departement (ecole_id)');
        $this->addSql('DROP INDEX IDX_EB4C4D4E419C3385');
        $this->addSql('CREATE TEMPORARY TABLE __temp__diplome AS SELECT id, pole_id, nom, nb_annee, niveau_diplome FROM diplome');
        $this->addSql('DROP TABLE diplome');
        $this->addSql('CREATE TABLE diplome (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, pole_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL COLLATE BINARY, nb_annee INTEGER NOT NULL, niveau_diplome VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_EB4C4D4E419C3385 FOREIGN KEY (pole_id) REFERENCES pole (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO diplome (id, pole_id, nom, nb_annee, niveau_diplome) SELECT id, pole_id, nom, nb_annee, niveau_diplome FROM __temp__diplome');
        $this->addSql('DROP TABLE __temp__diplome');
        $this->addSql('CREATE INDEX IDX_EB4C4D4E419C3385 ON diplome (pole_id)');
        $this->addSql('DROP INDEX IDX_4B98C21139DF194');
        $this->addSql('CREATE TEMPORARY TABLE __temp__groupe AS SELECT id, promotion_id, type FROM groupe');
        $this->addSql('DROP TABLE groupe');
        $this->addSql('CREATE TABLE groupe (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, promotion_id INTEGER NOT NULL, type VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_4B98C21139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO groupe (id, promotion_id, type) SELECT id, promotion_id, type FROM __temp__groupe');
        $this->addSql('DROP TABLE __temp__groupe');
        $this->addSql('CREATE INDEX IDX_4B98C21139DF194 ON groupe (promotion_id)');
        $this->addSql('DROP INDEX UNIQ_664B5989A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__info_etudiant AS SELECT id, user_id, num_etu, regime_special, adresse_etu FROM info_etudiant');
        $this->addSql('DROP TABLE info_etudiant');
        $this->addSql('CREATE TABLE info_etudiant (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, num_etu VARCHAR(255) NOT NULL COLLATE BINARY, regime_special VARCHAR(255) DEFAULT NULL COLLATE BINARY, adresse_etu VARCHAR(255) DEFAULT NULL COLLATE BINARY, CONSTRAINT FK_664B5989A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO info_etudiant (id, user_id, num_etu, regime_special, adresse_etu) SELECT id, user_id, num_etu, regime_special, adresse_etu FROM __temp__info_etudiant');
        $this->addSql('DROP TABLE __temp__info_etudiant');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_664B5989A76ED395 ON info_etudiant (user_id)');
        $this->addSql('DROP INDEX IDX_D8FDF019DDEAB1A3');
        $this->addSql('DROP INDEX IDX_D8FDF019A90F02B2');
        $this->addSql('DROP INDEX IDX_D8FDF019E455FCC0');
        $this->addSql('CREATE TEMPORARY TABLE __temp__inscription_semestre AS SELECT id, etudiant_id, secretaire_id, enseignant_id, annee_scolaire, as_tier_temp, as_rse, as_valide, as_transmise, message_prof, regime FROM inscription_semestre');
        $this->addSql('DROP TABLE inscription_semestre');
        $this->addSql('CREATE TABLE inscription_semestre (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, etudiant_id INTEGER NOT NULL, secretaire_id INTEGER DEFAULT NULL, enseignant_id INTEGER DEFAULT NULL, annee_scolaire VARCHAR(255) NOT NULL COLLATE BINARY, as_tier_temp BOOLEAN NOT NULL, as_rse BOOLEAN NOT NULL, as_valide BOOLEAN DEFAULT NULL, as_transmise BOOLEAN NOT NULL, message_prof CLOB DEFAULT NULL COLLATE BINARY, regime VARCHAR(255) DEFAULT NULL COLLATE BINARY, CONSTRAINT FK_D8FDF019DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_D8FDF019A90F02B2 FOREIGN KEY (secretaire_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_D8FDF019E455FCC0 FOREIGN KEY (enseignant_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO inscription_semestre (id, etudiant_id, secretaire_id, enseignant_id, annee_scolaire, as_tier_temp, as_rse, as_valide, as_transmise, message_prof, regime) SELECT id, etudiant_id, secretaire_id, enseignant_id, annee_scolaire, as_tier_temp, as_rse, as_valide, as_transmise, message_prof, regime FROM __temp__inscription_semestre');
        $this->addSql('DROP TABLE __temp__inscription_semestre');
        $this->addSql('CREATE INDEX IDX_D8FDF019DDEAB1A3 ON inscription_semestre (etudiant_id)');
        $this->addSql('CREATE INDEX IDX_D8FDF019A90F02B2 ON inscription_semestre (secretaire_id)');
        $this->addSql('CREATE INDEX IDX_D8FDF019E455FCC0 ON inscription_semestre (enseignant_id)');
        $this->addSql('DROP INDEX UNIQ_E20259CDD9F966B');
        $this->addSql('DROP INDEX IDX_E20259CD26F859E2');
        $this->addSql('CREATE TEMPORARY TABLE __temp__mention AS SELECT id, diplome_id, description_id, nom FROM mention');
        $this->addSql('DROP TABLE mention');
        $this->addSql('CREATE TABLE mention (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, diplome_id INTEGER NOT NULL, description_id INTEGER DEFAULT NULL, nom VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_E20259CD26F859E2 FOREIGN KEY (diplome_id) REFERENCES diplome (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E20259CDD9F966B FOREIGN KEY (description_id) REFERENCES parcours (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO mention (id, diplome_id, description_id, nom) SELECT id, diplome_id, description_id, nom FROM __temp__mention');
        $this->addSql('DROP TABLE __temp__mention');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E20259CDD9F966B ON mention (description_id)');
        $this->addSql('CREATE INDEX IDX_E20259CD26F859E2 ON mention (diplome_id)');
        $this->addSql('DROP INDEX IDX_C24262862E883B1');
        $this->addSql('CREATE TEMPORARY TABLE __temp__module AS SELECT id, ue_id, nom, as_obligatoire, ects, coef FROM module');
        $this->addSql('DROP TABLE module');
        $this->addSql('CREATE TABLE module (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ue_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL COLLATE BINARY, as_obligatoire BOOLEAN NOT NULL, ects INTEGER NOT NULL, coef INTEGER NOT NULL, CONSTRAINT FK_C24262862E883B1 FOREIGN KEY (ue_id) REFERENCES ue (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO module (id, ue_id, nom, as_obligatoire, ects, coef) SELECT id, ue_id, nom, as_obligatoire, ects, coef FROM __temp__module');
        $this->addSql('DROP TABLE __temp__module');
        $this->addSql('CREATE INDEX IDX_C24262862E883B1 ON module (ue_id)');
        $this->addSql('DROP INDEX IDX_FD710D1DAFC2B591');
        $this->addSql('DROP INDEX IDX_FD710D1D6E38C0DB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__module_parcours AS SELECT module_id, parcours_id FROM module_parcours');
        $this->addSql('DROP TABLE module_parcours');
        $this->addSql('CREATE TABLE module_parcours (module_id INTEGER NOT NULL, parcours_id INTEGER NOT NULL, PRIMARY KEY(module_id, parcours_id), CONSTRAINT FK_FD710D1DAFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_FD710D1D6E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcours (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO module_parcours (module_id, parcours_id) SELECT module_id, parcours_id FROM __temp__module_parcours');
        $this->addSql('DROP TABLE __temp__module_parcours');
        $this->addSql('CREATE INDEX IDX_FD710D1DAFC2B591 ON module_parcours (module_id)');
        $this->addSql('CREATE INDEX IDX_FD710D1D6E38C0DB ON module_parcours (parcours_id)');
        $this->addSql('DROP INDEX IDX_99B1DEE37A4147F0');
        $this->addSql('DROP INDEX UNIQ_99B1DEE3D9F966B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__parcours AS SELECT id, mention_id, description_id, nom FROM parcours');
        $this->addSql('DROP TABLE parcours');
        $this->addSql('CREATE TABLE parcours (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, mention_id INTEGER NOT NULL, description_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_99B1DEE37A4147F0 FOREIGN KEY (mention_id) REFERENCES mention (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_99B1DEE3D9F966B FOREIGN KEY (description_id) REFERENCES description (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO parcours (id, mention_id, description_id, nom) SELECT id, mention_id, description_id, nom FROM __temp__parcours');
        $this->addSql('DROP TABLE __temp__parcours');
        $this->addSql('CREATE INDEX IDX_99B1DEE37A4147F0 ON parcours (mention_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_99B1DEE3D9F966B ON parcours (description_id)');
        $this->addSql('DROP INDEX IDX_FD6042E1CCF9E01E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__pole AS SELECT id, departement_id, nom FROM pole');
        $this->addSql('DROP TABLE pole');
        $this->addSql('CREATE TABLE pole (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, departement_id INTEGER DEFAULT NULL, nom VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_FD6042E1CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO pole (id, departement_id, nom) SELECT id, departement_id, nom FROM __temp__pole');
        $this->addSql('DROP TABLE __temp__pole');
        $this->addSql('CREATE INDEX IDX_FD6042E1CCF9E01E ON pole (departement_id)');
        $this->addSql('DROP INDEX IDX_C11D7DD17A4147F0');
        $this->addSql('DROP INDEX IDX_C11D7DD1543EC5F0');
        $this->addSql('DROP INDEX IDX_C11D7DD16E38C0DB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__promotion AS SELECT id, annee_id, annee_scolaire FROM promotion');
        $this->addSql('DROP TABLE promotion');
        $this->addSql('CREATE TABLE promotion (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, semestre_id INTEGER NOT NULL, annee_scolaire VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_C11D7DD15577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO promotion (id, semestre_id, annee_scolaire) SELECT id, annee_id, annee_scolaire FROM __temp__promotion');
        $this->addSql('DROP TABLE __temp__promotion');
        $this->addSql('CREATE INDEX IDX_C11D7DD15577AFDB ON promotion (semestre_id)');
        $this->addSql('DROP INDEX IDX_3B695ED6139DF194');
        $this->addSql('DROP INDEX IDX_3B695ED6A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__promotion_user AS SELECT promotion_id, user_id FROM promotion_user');
        $this->addSql('DROP TABLE promotion_user');
        $this->addSql('CREATE TABLE promotion_user (promotion_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(promotion_id, user_id), CONSTRAINT FK_3B695ED6139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3B695ED6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO promotion_user (promotion_id, user_id) SELECT promotion_id, user_id FROM __temp__promotion_user');
        $this->addSql('DROP TABLE __temp__promotion_user');
        $this->addSql('CREATE INDEX IDX_3B695ED6139DF194 ON promotion_user (promotion_id)');
        $this->addSql('CREATE INDEX IDX_3B695ED6A76ED395 ON promotion_user (user_id)');
        $this->addSql('DROP INDEX IDX_C7CDC353A206320B');
        $this->addSql('DROP INDEX IDX_C7CDC353AFC2B591');
        $this->addSql('CREATE TEMPORARY TABLE __temp__proposition AS SELECT id, inscription_semestre_id, module_id, as_ajac FROM proposition');
        $this->addSql('DROP TABLE proposition');
        $this->addSql('CREATE TABLE proposition (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, inscription_semestre_id INTEGER NOT NULL, module_id INTEGER NOT NULL, as_ajac BOOLEAN NOT NULL, CONSTRAINT FK_C7CDC353A206320B FOREIGN KEY (inscription_semestre_id) REFERENCES inscription_semestre (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C7CDC353AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO proposition (id, inscription_semestre_id, module_id, as_ajac) SELECT id, inscription_semestre_id, module_id, as_ajac FROM __temp__proposition');
        $this->addSql('DROP TABLE __temp__proposition');
        $this->addSql('CREATE INDEX IDX_C7CDC353A206320B ON proposition (inscription_semestre_id)');
        $this->addSql('CREATE INDEX IDX_C7CDC353AFC2B591 ON proposition (module_id)');
        $this->addSql('DROP INDEX IDX_52520D07A76ED395');
        $this->addSql('DROP INDEX IDX_52520D0777EF1B1E');
        $this->addSql('DROP INDEX IDX_52520D07CCF9E01E');
        $this->addSql('DROP INDEX IDX_52520D07419C3385');
        $this->addSql('DROP INDEX IDX_52520D077A4147F0');
        $this->addSql('DROP INDEX IDX_52520D076E38C0DB');
        $this->addSql('DROP INDEX IDX_52520D07139DF194');
        $this->addSql('CREATE TEMPORARY TABLE __temp__responsable AS SELECT id, user_id, ecole_id, departement_id, pole_id, mention_id, parcours_id, promotion_id, annee_scolaire FROM responsable');
        $this->addSql('DROP TABLE responsable');
        $this->addSql('CREATE TABLE responsable (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER DEFAULT NULL, ecole_id INTEGER DEFAULT NULL, departement_id INTEGER DEFAULT NULL, pole_id INTEGER DEFAULT NULL, mention_id INTEGER DEFAULT NULL, parcours_id INTEGER DEFAULT NULL, promotion_id INTEGER DEFAULT NULL, annee_scolaire VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_52520D07A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_52520D0777EF1B1E FOREIGN KEY (ecole_id) REFERENCES ecole (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_52520D07CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_52520D07419C3385 FOREIGN KEY (pole_id) REFERENCES pole (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_52520D077A4147F0 FOREIGN KEY (mention_id) REFERENCES mention (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_52520D076E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcours (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_52520D07139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO responsable (id, user_id, ecole_id, departement_id, pole_id, mention_id, parcours_id, promotion_id, annee_scolaire) SELECT id, user_id, ecole_id, departement_id, pole_id, mention_id, parcours_id, promotion_id, annee_scolaire FROM __temp__responsable');
        $this->addSql('DROP TABLE __temp__responsable');
        $this->addSql('CREATE INDEX IDX_52520D07A76ED395 ON responsable (user_id)');
        $this->addSql('CREATE INDEX IDX_52520D0777EF1B1E ON responsable (ecole_id)');
        $this->addSql('CREATE INDEX IDX_52520D07CCF9E01E ON responsable (departement_id)');
        $this->addSql('CREATE INDEX IDX_52520D07419C3385 ON responsable (pole_id)');
        $this->addSql('CREATE INDEX IDX_52520D077A4147F0 ON responsable (mention_id)');
        $this->addSql('CREATE INDEX IDX_52520D076E38C0DB ON responsable (parcours_id)');
        $this->addSql('CREATE INDEX IDX_52520D07139DF194 ON responsable (promotion_id)');
        $this->addSql('DROP INDEX IDX_AFF9B77953C59D72');
        $this->addSql('DROP INDEX IDX_AFF9B779AFC2B591');
        $this->addSql('CREATE TEMPORARY TABLE __temp__responsable_module AS SELECT responsable_id, module_id FROM responsable_module');
        $this->addSql('DROP TABLE responsable_module');
        $this->addSql('CREATE TABLE responsable_module (responsable_id INTEGER NOT NULL, module_id INTEGER NOT NULL, PRIMARY KEY(responsable_id, module_id), CONSTRAINT FK_AFF9B77953C59D72 FOREIGN KEY (responsable_id) REFERENCES responsable (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_AFF9B779AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO responsable_module (responsable_id, module_id) SELECT responsable_id, module_id FROM __temp__responsable_module');
        $this->addSql('DROP TABLE __temp__responsable_module');
        $this->addSql('CREATE INDEX IDX_AFF9B77953C59D72 ON responsable_module (responsable_id)');
        $this->addSql('CREATE INDEX IDX_AFF9B779AFC2B591 ON responsable_module (module_id)');
        $this->addSql('DROP INDEX IDX_71688FBC6E38C0DB');
        $this->addSql('DROP INDEX IDX_71688FBC543EC5F0');
        $this->addSql('CREATE TEMPORARY TABLE __temp__semestre AS SELECT id, annee_id, parcours_id, nom FROM semestre');
        $this->addSql('DROP TABLE semestre');
        $this->addSql('CREATE TABLE semestre (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, annee_id INTEGER NOT NULL, parcours_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_71688FBC543EC5F0 FOREIGN KEY (annee_id) REFERENCES annee (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_71688FBC6E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcours (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO semestre (id, annee_id, parcours_id, nom) SELECT id, annee_id, parcours_id, nom FROM __temp__semestre');
        $this->addSql('DROP TABLE __temp__semestre');
        $this->addSql('CREATE INDEX IDX_71688FBC6E38C0DB ON semestre (parcours_id)');
        $this->addSql('CREATE INDEX IDX_71688FBC543EC5F0 ON semestre (annee_id)');
        $this->addSql('DROP INDEX IDX_2E490A9B5577AFDB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__ue AS SELECT id, semestre_id, nom FROM ue');
        $this->addSql('DROP TABLE ue');
        $this->addSql('CREATE TABLE ue (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, semestre_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_2E490A9B5577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO ue (id, semestre_id, nom) SELECT id, semestre_id, nom FROM __temp__ue');
        $this->addSql('DROP TABLE __temp__ue');
        $this->addSql('CREATE INDEX IDX_2E490A9B5577AFDB ON ue (semestre_id)');
        $this->addSql('DROP INDEX IDX_69763D15802A78E9');
        $this->addSql('DROP INDEX IDX_69763D15AFC2B591');
        $this->addSql('CREATE TEMPORARY TABLE __temp__user_module AS SELECT id, user_ue_id, module_id, as_ajac, moyenne FROM user_module');
        $this->addSql('DROP TABLE user_module');
        $this->addSql('CREATE TABLE user_module (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_ue_id INTEGER NOT NULL, module_id INTEGER NOT NULL, as_ajac BOOLEAN NOT NULL, moyenne INTEGER DEFAULT NULL, CONSTRAINT FK_69763D15802A78E9 FOREIGN KEY (user_ue_id) REFERENCES user_ue (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_69763D15AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO user_module (id, user_ue_id, module_id, as_ajac, moyenne) SELECT id, user_ue_id, module_id, as_ajac, moyenne FROM __temp__user_module');
        $this->addSql('DROP TABLE __temp__user_module');
        $this->addSql('CREATE INDEX IDX_69763D15802A78E9 ON user_module (user_ue_id)');
        $this->addSql('CREATE INDEX IDX_69763D15AFC2B591 ON user_module (module_id)');
        $this->addSql('DROP INDEX IDX_91E56BBC139DF194');
        $this->addSql('DROP INDEX IDX_91E56BBCDDEAB1A3');
        $this->addSql('DROP INDEX IDX_91E56BBC543EC5F0');
        $this->addSql('DROP INDEX IDX_91E56BBC5577AFDB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__user_semestre AS SELECT id, promotion_id, etudiant_id, annee_id, semestre_id, as_ajac, as_valide FROM user_semestre');
        $this->addSql('DROP TABLE user_semestre');
        $this->addSql('CREATE TABLE user_semestre (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, promotion_id INTEGER NOT NULL, etudiant_id INTEGER NOT NULL, annee_id INTEGER NOT NULL, semestre_id INTEGER NOT NULL, as_ajac BOOLEAN DEFAULT NULL, as_valide BOOLEAN DEFAULT NULL, CONSTRAINT FK_91E56BBC139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_91E56BBCDDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_91E56BBC543EC5F0 FOREIGN KEY (annee_id) REFERENCES annee (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_91E56BBC5577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO user_semestre (id, promotion_id, etudiant_id, annee_id, semestre_id, as_ajac, as_valide) SELECT id, promotion_id, etudiant_id, annee_id, semestre_id, as_ajac, as_valide FROM __temp__user_semestre');
        $this->addSql('DROP TABLE __temp__user_semestre');
        $this->addSql('CREATE INDEX IDX_91E56BBC139DF194 ON user_semestre (promotion_id)');
        $this->addSql('CREATE INDEX IDX_91E56BBCDDEAB1A3 ON user_semestre (etudiant_id)');
        $this->addSql('CREATE INDEX IDX_91E56BBC543EC5F0 ON user_semestre (annee_id)');
        $this->addSql('CREATE INDEX IDX_91E56BBC5577AFDB ON user_semestre (semestre_id)');
        $this->addSql('DROP INDEX IDX_361EBE5EFC6C664E');
        $this->addSql('DROP INDEX IDX_361EBE5E62E883B1');
        $this->addSql('CREATE TEMPORARY TABLE __temp__user_ue AS SELECT id, user_semestre_id, ue_id FROM user_ue');
        $this->addSql('DROP TABLE user_ue');
        $this->addSql('CREATE TABLE user_ue (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_semestre_id INTEGER NOT NULL, ue_id INTEGER NOT NULL, CONSTRAINT FK_361EBE5EFC6C664E FOREIGN KEY (user_semestre_id) REFERENCES user_semestre (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_361EBE5E62E883B1 FOREIGN KEY (ue_id) REFERENCES ue (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO user_ue (id, user_semestre_id, ue_id) SELECT id, user_semestre_id, ue_id FROM __temp__user_ue');
        $this->addSql('DROP TABLE __temp__user_ue');
        $this->addSql('CREATE INDEX IDX_361EBE5EFC6C664E ON user_ue (user_semestre_id)');
        $this->addSql('CREATE INDEX IDX_361EBE5E62E883B1 ON user_ue (ue_id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX IDX_DE92C5CF26F859E2');
        $this->addSql('CREATE TEMPORARY TABLE __temp__annee AS SELECT id, diplome_id, nom, numero_annee FROM annee');
        $this->addSql('DROP TABLE annee');
        $this->addSql('CREATE TABLE annee (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, diplome_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL, numero_annee INTEGER NOT NULL)');
        $this->addSql('INSERT INTO annee (id, diplome_id, nom, numero_annee) SELECT id, diplome_id, nom, numero_annee FROM __temp__annee');
        $this->addSql('DROP TABLE __temp__annee');
        $this->addSql('CREATE INDEX IDX_DE92C5CF26F859E2 ON annee (diplome_id)');
        $this->addSql('DROP INDEX IDX_C1765B6377EF1B1E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__departement AS SELECT id, ecole_id, nom FROM departement');
        $this->addSql('DROP TABLE departement');
        $this->addSql('CREATE TABLE departement (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ecole_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO departement (id, ecole_id, nom) SELECT id, ecole_id, nom FROM __temp__departement');
        $this->addSql('DROP TABLE __temp__departement');
        $this->addSql('CREATE INDEX IDX_C1765B6377EF1B1E ON departement (ecole_id)');
        $this->addSql('DROP INDEX IDX_EB4C4D4E419C3385');
        $this->addSql('CREATE TEMPORARY TABLE __temp__diplome AS SELECT id, pole_id, nom, nb_annee, niveau_diplome FROM diplome');
        $this->addSql('DROP TABLE diplome');
        $this->addSql('CREATE TABLE diplome (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, pole_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL, nb_annee INTEGER NOT NULL, niveau_diplome VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO diplome (id, pole_id, nom, nb_annee, niveau_diplome) SELECT id, pole_id, nom, nb_annee, niveau_diplome FROM __temp__diplome');
        $this->addSql('DROP TABLE __temp__diplome');
        $this->addSql('CREATE INDEX IDX_EB4C4D4E419C3385 ON diplome (pole_id)');
        $this->addSql('DROP INDEX IDX_4B98C21139DF194');
        $this->addSql('CREATE TEMPORARY TABLE __temp__groupe AS SELECT id, promotion_id, type FROM groupe');
        $this->addSql('DROP TABLE groupe');
        $this->addSql('CREATE TABLE groupe (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, promotion_id INTEGER NOT NULL, type VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO groupe (id, promotion_id, type) SELECT id, promotion_id, type FROM __temp__groupe');
        $this->addSql('DROP TABLE __temp__groupe');
        $this->addSql('CREATE INDEX IDX_4B98C21139DF194 ON groupe (promotion_id)');
        $this->addSql('DROP INDEX UNIQ_664B5989A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__info_etudiant AS SELECT id, user_id, num_etu, regime_special, adresse_etu FROM info_etudiant');
        $this->addSql('DROP TABLE info_etudiant');
        $this->addSql('CREATE TABLE info_etudiant (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, num_etu VARCHAR(255) NOT NULL, regime_special VARCHAR(255) DEFAULT NULL, adresse_etu VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO info_etudiant (id, user_id, num_etu, regime_special, adresse_etu) SELECT id, user_id, num_etu, regime_special, adresse_etu FROM __temp__info_etudiant');
        $this->addSql('DROP TABLE __temp__info_etudiant');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_664B5989A76ED395 ON info_etudiant (user_id)');
        $this->addSql('DROP INDEX IDX_D8FDF019DDEAB1A3');
        $this->addSql('DROP INDEX IDX_D8FDF019A90F02B2');
        $this->addSql('DROP INDEX IDX_D8FDF019E455FCC0');
        $this->addSql('CREATE TEMPORARY TABLE __temp__inscription_semestre AS SELECT id, etudiant_id, secretaire_id, enseignant_id, annee_scolaire, as_tier_temp, as_rse, as_valide, as_transmise, message_prof, regime FROM inscription_semestre');
        $this->addSql('DROP TABLE inscription_semestre');
        $this->addSql('CREATE TABLE inscription_semestre (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, etudiant_id INTEGER NOT NULL, secretaire_id INTEGER DEFAULT NULL, enseignant_id INTEGER DEFAULT NULL, annee_scolaire VARCHAR(255) NOT NULL, as_tier_temp BOOLEAN NOT NULL, as_rse BOOLEAN NOT NULL, as_valide BOOLEAN DEFAULT NULL, as_transmise BOOLEAN NOT NULL, message_prof CLOB DEFAULT NULL, regime VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO inscription_semestre (id, etudiant_id, secretaire_id, enseignant_id, annee_scolaire, as_tier_temp, as_rse, as_valide, as_transmise, message_prof, regime) SELECT id, etudiant_id, secretaire_id, enseignant_id, annee_scolaire, as_tier_temp, as_rse, as_valide, as_transmise, message_prof, regime FROM __temp__inscription_semestre');
        $this->addSql('DROP TABLE __temp__inscription_semestre');
        $this->addSql('CREATE INDEX IDX_D8FDF019DDEAB1A3 ON inscription_semestre (etudiant_id)');
        $this->addSql('CREATE INDEX IDX_D8FDF019A90F02B2 ON inscription_semestre (secretaire_id)');
        $this->addSql('CREATE INDEX IDX_D8FDF019E455FCC0 ON inscription_semestre (enseignant_id)');
        $this->addSql('DROP INDEX IDX_E20259CD26F859E2');
        $this->addSql('DROP INDEX UNIQ_E20259CDD9F966B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__mention AS SELECT id, diplome_id, description_id, nom FROM mention');
        $this->addSql('DROP TABLE mention');
        $this->addSql('CREATE TABLE mention (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, diplome_id INTEGER NOT NULL, description_id INTEGER DEFAULT NULL, nom VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO mention (id, diplome_id, description_id, nom) SELECT id, diplome_id, description_id, nom FROM __temp__mention');
        $this->addSql('DROP TABLE __temp__mention');
        $this->addSql('CREATE INDEX IDX_E20259CD26F859E2 ON mention (diplome_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E20259CDD9F966B ON mention (description_id)');
        $this->addSql('DROP INDEX IDX_C24262862E883B1');
        $this->addSql('CREATE TEMPORARY TABLE __temp__module AS SELECT id, ue_id, nom, as_obligatoire, ects, coef FROM module');
        $this->addSql('DROP TABLE module');
        $this->addSql('CREATE TABLE module (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ue_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL, as_obligatoire BOOLEAN NOT NULL, ects INTEGER NOT NULL, coef INTEGER NOT NULL)');
        $this->addSql('INSERT INTO module (id, ue_id, nom, as_obligatoire, ects, coef) SELECT id, ue_id, nom, as_obligatoire, ects, coef FROM __temp__module');
        $this->addSql('DROP TABLE __temp__module');
        $this->addSql('CREATE INDEX IDX_C24262862E883B1 ON module (ue_id)');
        $this->addSql('DROP INDEX IDX_FD710D1DAFC2B591');
        $this->addSql('DROP INDEX IDX_FD710D1D6E38C0DB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__module_parcours AS SELECT module_id, parcours_id FROM module_parcours');
        $this->addSql('DROP TABLE module_parcours');
        $this->addSql('CREATE TABLE module_parcours (module_id INTEGER NOT NULL, parcours_id INTEGER NOT NULL, PRIMARY KEY(module_id, parcours_id))');
        $this->addSql('INSERT INTO module_parcours (module_id, parcours_id) SELECT module_id, parcours_id FROM __temp__module_parcours');
        $this->addSql('DROP TABLE __temp__module_parcours');
        $this->addSql('CREATE INDEX IDX_FD710D1DAFC2B591 ON module_parcours (module_id)');
        $this->addSql('CREATE INDEX IDX_FD710D1D6E38C0DB ON module_parcours (parcours_id)');
        $this->addSql('DROP INDEX IDX_99B1DEE37A4147F0');
        $this->addSql('DROP INDEX UNIQ_99B1DEE3D9F966B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__parcours AS SELECT id, mention_id, description_id, nom FROM parcours');
        $this->addSql('DROP TABLE parcours');
        $this->addSql('CREATE TABLE parcours (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, mention_id INTEGER NOT NULL, description_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO parcours (id, mention_id, description_id, nom) SELECT id, mention_id, description_id, nom FROM __temp__parcours');
        $this->addSql('DROP TABLE __temp__parcours');
        $this->addSql('CREATE INDEX IDX_99B1DEE37A4147F0 ON parcours (mention_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_99B1DEE3D9F966B ON parcours (description_id)');
        $this->addSql('DROP INDEX IDX_FD6042E1CCF9E01E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__pole AS SELECT id, departement_id, nom FROM pole');
        $this->addSql('DROP TABLE pole');
        $this->addSql('CREATE TABLE pole (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, departement_id INTEGER DEFAULT NULL, nom VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO pole (id, departement_id, nom) SELECT id, departement_id, nom FROM __temp__pole');
        $this->addSql('DROP TABLE __temp__pole');
        $this->addSql('CREATE INDEX IDX_FD6042E1CCF9E01E ON pole (departement_id)');
        $this->addSql('DROP INDEX IDX_C11D7DD15577AFDB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__promotion AS SELECT id, semestre_id, annee_scolaire FROM promotion');
        $this->addSql('DROP TABLE promotion');
        $this->addSql('CREATE TABLE promotion (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, annee_scolaire VARCHAR(255) NOT NULL, annee_id INTEGER NOT NULL, mention_id INTEGER DEFAULT NULL, parcours_id INTEGER DEFAULT NULL)');
        $this->addSql('INSERT INTO promotion (id, annee_id, annee_scolaire) SELECT id, semestre_id, annee_scolaire FROM __temp__promotion');
        $this->addSql('DROP TABLE __temp__promotion');
        $this->addSql('CREATE INDEX IDX_C11D7DD17A4147F0 ON promotion (mention_id)');
        $this->addSql('CREATE INDEX IDX_C11D7DD1543EC5F0 ON promotion (annee_id)');
        $this->addSql('CREATE INDEX IDX_C11D7DD16E38C0DB ON promotion (parcours_id)');
        $this->addSql('DROP INDEX IDX_3B695ED6139DF194');
        $this->addSql('DROP INDEX IDX_3B695ED6A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__promotion_user AS SELECT promotion_id, user_id FROM promotion_user');
        $this->addSql('DROP TABLE promotion_user');
        $this->addSql('CREATE TABLE promotion_user (promotion_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(promotion_id, user_id))');
        $this->addSql('INSERT INTO promotion_user (promotion_id, user_id) SELECT promotion_id, user_id FROM __temp__promotion_user');
        $this->addSql('DROP TABLE __temp__promotion_user');
        $this->addSql('CREATE INDEX IDX_3B695ED6139DF194 ON promotion_user (promotion_id)');
        $this->addSql('CREATE INDEX IDX_3B695ED6A76ED395 ON promotion_user (user_id)');
        $this->addSql('DROP INDEX IDX_C7CDC353A206320B');
        $this->addSql('DROP INDEX IDX_C7CDC353AFC2B591');
        $this->addSql('CREATE TEMPORARY TABLE __temp__proposition AS SELECT id, inscription_semestre_id, module_id, as_ajac FROM proposition');
        $this->addSql('DROP TABLE proposition');
        $this->addSql('CREATE TABLE proposition (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, inscription_semestre_id INTEGER NOT NULL, module_id INTEGER NOT NULL, as_ajac BOOLEAN NOT NULL)');
        $this->addSql('INSERT INTO proposition (id, inscription_semestre_id, module_id, as_ajac) SELECT id, inscription_semestre_id, module_id, as_ajac FROM __temp__proposition');
        $this->addSql('DROP TABLE __temp__proposition');
        $this->addSql('CREATE INDEX IDX_C7CDC353A206320B ON proposition (inscription_semestre_id)');
        $this->addSql('CREATE INDEX IDX_C7CDC353AFC2B591 ON proposition (module_id)');
        $this->addSql('DROP INDEX IDX_52520D07A76ED395');
        $this->addSql('DROP INDEX IDX_52520D0777EF1B1E');
        $this->addSql('DROP INDEX IDX_52520D07CCF9E01E');
        $this->addSql('DROP INDEX IDX_52520D07419C3385');
        $this->addSql('DROP INDEX IDX_52520D077A4147F0');
        $this->addSql('DROP INDEX IDX_52520D076E38C0DB');
        $this->addSql('DROP INDEX IDX_52520D07139DF194');
        $this->addSql('CREATE TEMPORARY TABLE __temp__responsable AS SELECT id, user_id, ecole_id, departement_id, pole_id, mention_id, parcours_id, promotion_id, annee_scolaire FROM responsable');
        $this->addSql('DROP TABLE responsable');
        $this->addSql('CREATE TABLE responsable (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER DEFAULT NULL, ecole_id INTEGER DEFAULT NULL, departement_id INTEGER DEFAULT NULL, pole_id INTEGER DEFAULT NULL, mention_id INTEGER DEFAULT NULL, parcours_id INTEGER DEFAULT NULL, promotion_id INTEGER DEFAULT NULL, annee_scolaire VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO responsable (id, user_id, ecole_id, departement_id, pole_id, mention_id, parcours_id, promotion_id, annee_scolaire) SELECT id, user_id, ecole_id, departement_id, pole_id, mention_id, parcours_id, promotion_id, annee_scolaire FROM __temp__responsable');
        $this->addSql('DROP TABLE __temp__responsable');
        $this->addSql('CREATE INDEX IDX_52520D07A76ED395 ON responsable (user_id)');
        $this->addSql('CREATE INDEX IDX_52520D0777EF1B1E ON responsable (ecole_id)');
        $this->addSql('CREATE INDEX IDX_52520D07CCF9E01E ON responsable (departement_id)');
        $this->addSql('CREATE INDEX IDX_52520D07419C3385 ON responsable (pole_id)');
        $this->addSql('CREATE INDEX IDX_52520D077A4147F0 ON responsable (mention_id)');
        $this->addSql('CREATE INDEX IDX_52520D076E38C0DB ON responsable (parcours_id)');
        $this->addSql('CREATE INDEX IDX_52520D07139DF194 ON responsable (promotion_id)');
        $this->addSql('DROP INDEX IDX_AFF9B77953C59D72');
        $this->addSql('DROP INDEX IDX_AFF9B779AFC2B591');
        $this->addSql('CREATE TEMPORARY TABLE __temp__responsable_module AS SELECT responsable_id, module_id FROM responsable_module');
        $this->addSql('DROP TABLE responsable_module');
        $this->addSql('CREATE TABLE responsable_module (responsable_id INTEGER NOT NULL, module_id INTEGER NOT NULL, PRIMARY KEY(responsable_id, module_id))');
        $this->addSql('INSERT INTO responsable_module (responsable_id, module_id) SELECT responsable_id, module_id FROM __temp__responsable_module');
        $this->addSql('DROP TABLE __temp__responsable_module');
        $this->addSql('CREATE INDEX IDX_AFF9B77953C59D72 ON responsable_module (responsable_id)');
        $this->addSql('CREATE INDEX IDX_AFF9B779AFC2B591 ON responsable_module (module_id)');
        $this->addSql('DROP INDEX IDX_71688FBC543EC5F0');
        $this->addSql('DROP INDEX IDX_71688FBC6E38C0DB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__semestre AS SELECT id, annee_id, parcours_id, nom FROM semestre');
        $this->addSql('DROP TABLE semestre');
        $this->addSql('CREATE TABLE semestre (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, annee_id INTEGER NOT NULL, parcours_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO semestre (id, annee_id, parcours_id, nom) SELECT id, annee_id, parcours_id, nom FROM __temp__semestre');
        $this->addSql('DROP TABLE __temp__semestre');
        $this->addSql('CREATE INDEX IDX_71688FBC543EC5F0 ON semestre (annee_id)');
        $this->addSql('CREATE INDEX IDX_71688FBC6E38C0DB ON semestre (parcours_id)');
        $this->addSql('DROP INDEX IDX_2E490A9B5577AFDB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__ue AS SELECT id, semestre_id, nom FROM ue');
        $this->addSql('DROP TABLE ue');
        $this->addSql('CREATE TABLE ue (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, semestre_id INTEGER NOT NULL, nom VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO ue (id, semestre_id, nom) SELECT id, semestre_id, nom FROM __temp__ue');
        $this->addSql('DROP TABLE __temp__ue');
        $this->addSql('CREATE INDEX IDX_2E490A9B5577AFDB ON ue (semestre_id)');
        $this->addSql('DROP INDEX IDX_69763D15802A78E9');
        $this->addSql('DROP INDEX IDX_69763D15AFC2B591');
        $this->addSql('CREATE TEMPORARY TABLE __temp__user_module AS SELECT id, user_ue_id, module_id, as_ajac, moyenne FROM user_module');
        $this->addSql('DROP TABLE user_module');
        $this->addSql('CREATE TABLE user_module (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_ue_id INTEGER NOT NULL, module_id INTEGER NOT NULL, as_ajac BOOLEAN NOT NULL, moyenne INTEGER DEFAULT NULL)');
        $this->addSql('INSERT INTO user_module (id, user_ue_id, module_id, as_ajac, moyenne) SELECT id, user_ue_id, module_id, as_ajac, moyenne FROM __temp__user_module');
        $this->addSql('DROP TABLE __temp__user_module');
        $this->addSql('CREATE INDEX IDX_69763D15802A78E9 ON user_module (user_ue_id)');
        $this->addSql('CREATE INDEX IDX_69763D15AFC2B591 ON user_module (module_id)');
        $this->addSql('DROP INDEX IDX_91E56BBC139DF194');
        $this->addSql('DROP INDEX IDX_91E56BBCDDEAB1A3');
        $this->addSql('DROP INDEX IDX_91E56BBC543EC5F0');
        $this->addSql('DROP INDEX IDX_91E56BBC5577AFDB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__user_semestre AS SELECT id, promotion_id, etudiant_id, annee_id, semestre_id, as_ajac, as_valide FROM user_semestre');
        $this->addSql('DROP TABLE user_semestre');
        $this->addSql('CREATE TABLE user_semestre (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, promotion_id INTEGER NOT NULL, etudiant_id INTEGER NOT NULL, annee_id INTEGER NOT NULL, semestre_id INTEGER NOT NULL, as_ajac BOOLEAN DEFAULT NULL, as_valide BOOLEAN DEFAULT NULL)');
        $this->addSql('INSERT INTO user_semestre (id, promotion_id, etudiant_id, annee_id, semestre_id, as_ajac, as_valide) SELECT id, promotion_id, etudiant_id, annee_id, semestre_id, as_ajac, as_valide FROM __temp__user_semestre');
        $this->addSql('DROP TABLE __temp__user_semestre');
        $this->addSql('CREATE INDEX IDX_91E56BBC139DF194 ON user_semestre (promotion_id)');
        $this->addSql('CREATE INDEX IDX_91E56BBCDDEAB1A3 ON user_semestre (etudiant_id)');
        $this->addSql('CREATE INDEX IDX_91E56BBC543EC5F0 ON user_semestre (annee_id)');
        $this->addSql('CREATE INDEX IDX_91E56BBC5577AFDB ON user_semestre (semestre_id)');
        $this->addSql('DROP INDEX IDX_361EBE5EFC6C664E');
        $this->addSql('DROP INDEX IDX_361EBE5E62E883B1');
        $this->addSql('CREATE TEMPORARY TABLE __temp__user_ue AS SELECT id, user_semestre_id, ue_id FROM user_ue');
        $this->addSql('DROP TABLE user_ue');
        $this->addSql('CREATE TABLE user_ue (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_semestre_id INTEGER NOT NULL, ue_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO user_ue (id, user_semestre_id, ue_id) SELECT id, user_semestre_id, ue_id FROM __temp__user_ue');
        $this->addSql('DROP TABLE __temp__user_ue');
        $this->addSql('CREATE INDEX IDX_361EBE5EFC6C664E ON user_ue (user_semestre_id)');
        $this->addSql('CREATE INDEX IDX_361EBE5E62E883B1 ON user_ue (ue_id)');
    }
}
